### ISSUE TITLE
JSON response error

### ISSUE THREAD

**Issue by ivanvermeyen** [JacobBennett/laravel-HTTP2ServerPush#11]
Hi,

First, thanks for creating this awesome package!

I noticed you already added a check for JSON responses in [this commit](https://github.com/JacobBennett/laravel-HTTP2ServerPush/commit/ba295d23e307fa5066ae36b6ad0191357935c0df).

I just bumped onto this JSON problem while I was trying to write some tests for my project...

`Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to JacobBennett\Http2ServerPush\Middleware\AddHttp2ServerPush::generateAndAttachLinkHeaders() must be an instance of Illuminate\Http\Response, instance of Illuminate\Http\JsonResponse given`

Will you be tagging the latest commits in a new release soon?

👍

**Comment by JacobBennett** [comment]
Just now tagged version 1.3 for you :) Thanks for the heads up. Didn't realize I hadn't tagged it yet. Thanks for reaching out.
