### ISSUE TITLE
Wrong type comparison in Laravel 5.3

### ISSUE THREAD

**Issue by ovanschie** [JacobBennett/laravel-HTTP2ServerPush#12]
Hi,

I tried this package in a Laravel 5.3 app and found that the assets url where compared against the 'type' (style, script, image) in stead of the extension (.CSS, .JS, etc..).

This change fixed it for me:
https://github.com/appstract/laravel-HTTP2ServerPush/commit/724269aa4b90000453a78315ea8f323f295f642d

But I don't know if this will play nice with older Laravel versions?

**Comment by GrahamCampbell** [comment]
I don't think your commit will work on all laravel versions.

**Comment by rasmuscnielsen** [comment]
@GrahamCampbell 
It most likely will only work 5.3+5.4. However this is indeed a valid fix, as the package does not work in these versions as is.

A suggestion would be to make a new major version with this fix.

**Comment by juukie** [comment]
Having the same issue and would love to see this fixed :).
My temporary fix: https://paste.laravel.io/PyYlM

**Comment by JacobBennett** [comment]
Hey guys! Sorry I haven't responded to this sooner! Been busy dealing with a new member of our little fam! Going to take a look at this and see what I can do for you. Thanks for your support and for your patience!

**Comment by JacobBennett** [comment]
should be fixed in 51735807f342ad02a5a3f7713bb31ff32dc9e863

Tagged a new version v2.0.0 for now which should fix the issues. Thanks!

**Comment by juukie** [comment]
Thanks @JacobBennett, works like a charm.

**Comment by ovanschie** [comment]
@JacobBennett thanks for the response! Have you ever considered to transfer the package to someone else due to the lack of free time to spend on it? We would like to use this package in our future projects and like to change a thing or two. So maybe instead of using our own fork we could take it over from you?

All the luck to you and your family!

**Comment by JacobBennett** [comment]
@ovanschie I have not considered the transfer up to this point no. Would love it if you could pull request your features into this repo though, and we could pull it in. Hoping to have a little more time soon so could look them over more quickly. If still not able to keep up with it, maybe we could have that discussion in the future! Thanks for the offer and for the well wishes for the fam.

**Comment by ovanschie** [comment]
@JacobBennett that's cool 👍
