### ISSUE TITLE
Unclear documentation on usage

### ISSUE THREAD

**Issue by ujwaldhakal** [JacobBennett/laravel-HTTP2ServerPush#13]
Would it work by simply adding the class to kernel or need to configure more. As my push state is not working as it should.

**Comment by ctf0** [comment]
as its a middleware, then all u need is to add it under web,
note that http2 is only avail under https , so unless u have ssl ex.`localhost` it wont work

**Comment by JacobBennett** [comment]
Thanks for picking this up @ctf0. Yes if you just add it to the global middleware stack in the Kernel it should work assuming you have met the other requirements of HTTP2 Server Push.
