### ISSUE TITLE
Package overwrites Link header 

### ISSUE THREAD

**Issue by juukie** [JacobBennett/laravel-HTTP2ServerPush#18]
Currently I'm working on a multilanguage website where there is already a Link header set to the response:

`
<https://example.com/nl>; rel="alternate"; hreflang="nl",<https://example.com/en>; rel="alternate"; hreflang="en"
`

I was thinking about changing the `AddHttp2ServerPush::addLinkHeader()` method to prepend the Link header if already present:

```
if ($response->headers->get('Link')) {
    $link .= ',' . $response->headers->get('Link');
}

$response->header('Link', $link);
```

Of course I'll be able to extend the middleware and override the method. But would it be something to add to the core?

**Comment by JacobBennett** [comment]
Sure why not! As long as the test pass have no issue with that. Thanks @juukie 👍
