### ISSUE TITLE
Incompatible with Laravel 5.6

### ISSUE THREAD

**Issue by vongola12324** [JacobBennett/laravel-HTTP2ServerPush#22]
It seems we can not get the latest package from packagist when I'm using Laravel 5.6.
From the log, the latest release is v2.0.4, which is commit 75d9fd6, not ac84d27.
Could you publish a new release to let we use it in Laravel 5.6 project?
Thanks. 😄 

![](https://i.imgur.com/7gztURd.png)
See also #21.

**Comment by JacobBennett** [comment]
New release published! Thank you!
