### ISSUE TITLE
Premature end of script headers: ea-php71

### ISSUE THREAD

**Issue by erenmustafaozdal** [JacobBennett/laravel-HTTP2ServerPush#23]
I am grateful to you for the package you developed to improve performance, which is Laravel's worst point.

I got a "**Premature end of script headers: ea-php71**" error in a **Laravel 5.5** project running with **PHP 7.1** on **CENTOS 6.10 virtuozzo** (_CPanel WHM_).

Long research and debug operations at the end; The problem disappeared when I uninstalled the **laravel-HTTP2ServerPush** package.

In my research, it is stated that there is a problem with the header length sent to the server.

Do I need to make a setting when I use the package or a setting on the apache server?

Thanks, good work!

**Comment by Nuranto** [comment]
Have the same issue with Ubuntu 18.04 - apache2 - php-fpm

```
[Thu Dec 13 11:26:36.943319 2018] [proxy_fcgi:error] [pid 22902:tid 140233210566400] [client ***] Premature end of script headers: index.php, referer: ***
[Thu Dec 13 11:26:36.943405 2018] [proxy_fcgi:error] [pid 22902:tid 140233210566400] [client ***] AH01070: Error parsing script headers, referer: ***
[Thu Dec 13 11:26:36.943417 2018] [proxy_fcgi:error] [pid 22902:tid 140233210566400] (22)Invalid argument: [client ****] AH01075: Error dispatching request to : , referer: ***
```

Probably linked to : https://maxchadwick.xyz/blog/http-response-header-size-limit-with-mod-proxy-fcgi

Anyway, I think you should limit (using a config field) the size of the Link header.

#25 is related too. In my case, without duplicate, i would probably not reach the limit.

**Comment by JacobBennett** [comment]
Hopefully #26 will help to take care of this one, thank you for your contribution @Nuranto!

**Comment by Nuranto** [comment]
Still got the issue on large page, even with #26. I've just submitted a PR to limit the size of the link header.

**Comment by JacobBennett** [comment]
Thanks Nuranto!
