### ISSUE TITLE
Laravel 6.x dosn't install

### ISSUE THREAD

**Issue by paytrdev** [JacobBennett/laravel-HTTP2ServerPush#37]
![Ekran Resmi 2019-11-25 18 04 51](https://user-images.githubusercontent.com/56681429/69551783-54d20e80-0fae-11ea-820a-16d434421da0.png)

**Comment by adampatterson** [comment]
I would love to know if Laravel 6 is in the works.

**Comment by paytrdev** [comment]
my other modules depends 'symfony/css-selector' > ^5.0 and 'symfony/dom-crawler' > ^5.0 but this module depends  ^2.7|^3.0|^4.0 because of that dosn't install.please update module dependency.

**Comment by JacobBennett** [comment]
Fixed in https://github.com/JacobBennett/laravel-HTTP2ServerPush/releases/tag/v4.0.1
