### ISSUE TITLE
Packagist repo is not updated

### ISSUE THREAD

**Issue by f-liva** [JacobBennett/laravel-HTTP2ServerPush#40]
Your packagist repo is not updated to 4.0.2

https://packagist.org/packages/jacobbennett/laravel-http2serverpush

Maybe you have misconfigured the webhook?

**Comment by JacobBennett** [comment]
Just checked it, should be sorted

![image](https://user-images.githubusercontent.com/1517011/70032444-1d95cb80-1573-11ea-9bbb-ad81cf676363.png)
