### ISSUE TITLE
Fetch type not supported

### ISSUE THREAD

**Issue by biscofil** [JacobBennett/laravel-HTTP2ServerPush#45]
Hey!

I took a look at the code, good job!! However I noticed that resources with type "fetch" are not picked up as the **$linkTypeMap** array in **buildLinkHeaderString()** won't find any correspondence with those extensions.

Example:
` <link rel="preload" href="/api/events" as="fetch">`

Since api calls like that have no extension, would it be possible to set "fetch" as default in case no other file format matches? 

Thank you!

**Comment by JacobBennett** [comment]
Fixed in #46 thanks @biscofil!
