### ISSUE TITLE
502 bad gateway on pages with images

### ISSUE THREAD

**Issue by ctf0** [JacobBennett/laravel-HTTP2ServerPush#8]
not sure what exactly is the issue but for the pages that have images in it (mostly jpg) i get a nginx 502 error.

i tried the put the middleware in both `middleware & middlewareGroups` and both give the same error.

if u need any extra info plz do tell me.

**Comment by JacobBennett** [comment]
@ctf0 did you get this issue resolved??

**Comment by ctf0** [comment]
nop :(

**Comment by JacobBennett** [comment]
can you send me an example rendered html page with your image urls rendered in it? Just drop it in a gist and link it here?

**Comment by ctf0** [comment]
actually the issue is inconsistent , sometimes it happens when trying to simply switch from language to another & even this one is inconsistent from pc to another or os to another (mac & windows) , thats why i closed as it seems the package is interfering with something else more than just the s3 images 😞

**Comment by JacobBennett** [comment]
Have you looked in the logs to see what the Nginx error is sending there? Is there any info to indicate what might be failing?

**Comment by ctf0** [comment]
am new into the whole server management thing, am using forge and here are my current config
https://gist.github.com/ctf0/b3eb10d044b4a61861807646fdcd1bd3

if u could tell me how to get/view the nginx log i would really appreciate it

**Comment by hemratna** [comment]
Hi, @JacobBennett 
Even I also encounter this issue.
I think this issue is not with S3, But the issue with so many images on a page.
I have [Material Icons](https://www.materialui.co/icons) website, apart from icon page this packages work fine, but in icon page I have 25+ icon (.png) image. So this package gives 502 gateway error.
P.S. If I use SVG instead of png then it's working fine. (No 502 error).

Thanks for such an amazing package. :)

**Comment by ctf0** [comment]
@hemratna u r correct, i was using data:uri for images and all was good, once i started using image files i started getting the error.
but noticed some strange behavior , when the site opens all is good, when u try to go to another page with some other images i get the 502 error.

**Comment by JacobBennett** [comment]
Hmm... seems like there is a threshold for the amount of things that you can push through the links headers. I wonder what the upper limit for this is? 

It seems to me that what would be most helpful would be to order the assets to be delivered in this order.
1. CSS
2. JS
3. Images

until you reach a threshold. Say like 20 assets max, maybe 15 I dont know. I feel like after that many pushed assets, the html is going to be rendered and downloading the items as usual anyway. Thoughts?

**Comment by ctf0** [comment]
not sure if this would work but the scenario i currently have is

1- visit the site on `www.example.com\en` "no probs"
2- switch the lang to `www.example.com\fr` "u will get the error"

however if ur first land was on  `www.example.com\fr` u wont get any errors, only when u try to switch the lang.

**Comment by hemratna** [comment]
@JacobBennett using threshold is great.
We can also have some configuration something like push only CSS, or JS.

**Comment by JacobBennett** [comment]
@ctf0 that seems like an odd issue with the changing of languages... Are you sure this is an issue being caused by this middleware?

**Comment by JacobBennett** [comment]
@hemratna feel free to PR those changes. Think those would be good as well

**Comment by ctf0** [comment]
@JacobBennett yeap, because disabling the middleware solve the issue

**Comment by iggori** [comment]
Have same problem. On locale works fine but behind cloudflare 503. :(

**Comment by iggori** [comment]
Can you add some limit in config so we can adjust to max 50?
https://blog.cloudflare.com/http-2-server-push-with-multiple-assets-per-link-header/
"Please let us know how you use Server Push. We're particularly interested in experiences with pushing different types of resources (images vs. styles vs. scripts) and working out the optimal number of items to push (we currently allow up to 50 resources per page)."

**Comment by JacobBennett** [comment]
@iggori would welcome a PR on this. Would likely be implemented by having a `take()` call [somewhere after this](https://github.com/JacobBennett/laravel-HTTP2ServerPush/blob/master/src/Middleware/AddHttp2ServerPush.php#L52)

**Comment by morloderex** [comment]
@JacobBennett Maybe the error is related to this [here](https://github.com/JacobBennett/laravel-HTTP2ServerPush/blob/master/src/Middleware/AddHttp2ServerPush.php#L129). 

The reason for my thinking is that we are not setting the third parameter of the header method to **false** to force the headers to not overwrite eachother.

**Comment by ctf0** [comment]
@JacobBennett is it possible to make the package only work for Css & Js, trying to preload images is inefficient for more than one reason

- headers has limits for "size & length"
- for pages with too many images, server will take longer to process
- using js libs to manipulate the images on page load, will cuz issues for the server to handle it as sometimes those libs require place holders instead of the actual image

imho images preloading could make sense when used with something like `fav-icon` ex.

```html
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
```

but outside that its an unnecessary overhead.

**Comment by ctf0** [comment]
**UPDATE**

i think this may be related to `fastcgi buffer settings`, anyone can reproduce the issue, try changing that config and see if it works. [example](https://github.com/laravel/valet/issues/269#issuecomment-271928229)

if yes we can close this.

**Comment by HDVinnie** [comment]
any updates on this? Otherwise maybe best to cut the whole images logic out
