### ISSUE TITLE
Change Documentation for Web Group Only

### ISSUE THREAD

**Issue by tankerkiller125** [JacobBennett/laravel-HTTP2ServerPush#9]
It would seem to make sense that this middlware is only needed on the web group in Laravel 5.2 and 5.3 since the API doesn't/shouldn't normally return any assets the browser would need to display. And most API clients do not support HTTP2 Push in the first place. Would it make sense to change the documentation to reflect that fact?

**Comment by JacobBennett** [comment]
@tankerkiller125 Yes this would make sense. Feel free to submit a PR clarifying this and I would be happy to pull it in. Thanks! 👍

**Comment by tankerkiller125** [comment]
@JacobBennett Pull request #10

**Comment by JacobBennett** [comment]
Thanks for the PR
